# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kron-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kron-iOS

  target 'kron-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'kron-macOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kron-macOS

  target 'kron-macOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'kron-tvOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kron-tvOS

  target 'kron-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
